import { StyleSheet, Dimensions } from 'react-native';
import { colors, spacing, radius, shadows, fonts } from '../styles/theme';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  scanlines: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    opacity: 0.03,
    backgroundColor: 'transparent',
  },
  content: {
    width: '100%',
    alignItems: 'center',
  },
  logoWrap: {
    width: 72,
    height: 72,
    borderRadius: radius.sm,
    backgroundColor: colors.primaryDim,
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.lg,
    ...shadows.orange,
  },
  logoText: {
    fontSize: 36,
  },
  title: {
    fontFamily: fonts.pixel,
    fontSize: 16,
    color: colors.primary,
    textAlign: 'center',
    marginBottom: spacing.sm,
    lineHeight: 28,
    ...shadows.orange,
  },
  subtitle: {
    fontFamily: fonts.pixel,
    fontSize: 7,
    color: colors.accent,
    letterSpacing: 2,
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  divider: {
    width: '100%',
    height: 1,
    backgroundColor: colors.border,
    marginBottom: spacing.lg,
  },
  connectedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.accentDim,
    borderWidth: 1,
    borderColor: colors.accent,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: radius.none,
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  connectedDot: {
    width: 7,
    height: 7,
    backgroundColor: colors.accent,
  },
  connectedText: {
    color: colors.accent,
    fontFamily: fonts.pixel,
    fontSize: 8,
    letterSpacing: 1,
  },
  writeButton: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    paddingVertical: 18,
    borderRadius: radius.none,
    gap: spacing.sm,
    marginBottom: spacing.md,
    borderWidth: 2,
    borderColor: colors.white,
    ...shadows.orange,
  },
  writeButtonText: {
    color: colors.background,
    fontFamily: fonts.pixel,
    fontSize: 11,
    letterSpacing: 1,
  },
  statsRow: {
    width: '100%',
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing.md,
    justifyContent: 'space-around',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  statItem: {
    alignItems: 'center',
    gap: 6,
  },
  statValue: {
    color: colors.primary,
    fontFamily: fonts.pixel,
    fontSize: 10,
  },
  statLabel: {
    color: colors.grey1,
    fontSize: 8,
    fontFamily: fonts.pixel,
    letterSpacing: 1,
  },
  statDivider: {
    width: 1,
    height: 24,
    backgroundColor: colors.border,
  },
  disconnectButton: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderWidth: 1,
    borderColor: colors.grey2,
  },
  disconnectText: {
    color: colors.grey1,
    fontFamily: fonts.pixel,
    fontSize: 7,
    letterSpacing: 1,
  },
  tagline: {
    fontSize: 13,
    color: colors.grey1,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: spacing.lg,
    fontFamily: fonts.mono,
  },
  taglineHighlight: {
    color: colors.primary,
    fontFamily: fonts.pixel,
    fontSize: 11,
  },
  connectButton: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    paddingVertical: 18,
    borderRadius: radius.none,
    marginBottom: spacing.sm,
    borderWidth: 2,
    borderColor: colors.white,
    ...shadows.orange,
  },
  connectButtonText: {
    color: colors.background,
    fontFamily: fonts.pixel,
    fontSize: 11,
    letterSpacing: 1,
  },
  walletHint: {
    color: colors.grey2,
    fontFamily: fonts.pixel,
    fontSize: 6,
    letterSpacing: 1,
    textAlign: 'center',
  },
  bottomText: {
    position: 'absolute',
    bottom: 32,
    color: colors.grey2,
    fontFamily: fonts.pixel,
    fontSize: 6,
    letterSpacing: 2,
  },
  loadingText: {
    color: colors.primary,
    fontFamily: fonts.pixel,
    fontSize: 8,
    marginTop: spacing.md,
    letterSpacing: 1,
  },
  glowOrb: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: colors.primary,
    top: '-5%',
    alignSelf: 'center',
    opacity: 0.05,
  },
 logoImage: {
  width: 120,
  height: 120,
  marginBottom: spacing.md,
},
});