import { StyleSheet } from 'react-native';
import { colors, spacing, radius, fonts } from '../styles/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#080808',
  },
  scroll: {
    flexGrow: 1,
    padding: spacing.lg,
    paddingTop: 60,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backBtn: {
    fontFamily: fonts.pixel,
    fontSize: 7,
    color: colors.accent,
    textShadowColor: colors.accent,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  headerTitle: {
    fontFamily: fonts.pixel,
    fontSize: 9,
    color: colors.white,
    textShadowColor: '#FF8C00',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  headerTime: {
    fontFamily: fonts.mono,
    fontSize: 10,
    color: colors.grey1,
    fontWeight: '900',
  },
  sectionLabel: {
    fontFamily: fonts.pixel,
    fontSize: 7,
    color: colors.primary,
    marginBottom: spacing.sm,
    letterSpacing: 1,
    textShadowColor: colors.primary,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  inputBox: {
    backgroundColor: 'rgba(13,10,30,0.95)',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    padding: spacing.md,
    marginBottom: spacing.md,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  input: {
    fontFamily: fonts.mono,
    fontSize: 15,
    color: colors.white,
    minHeight: 160,
    textAlignVertical: 'top',
    lineHeight: 24,
    fontWeight: '900',
  },
  progressTrack: {
    height: 4,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: radius.sm,
  },
  progressFill: {
    height: '100%',
    borderRadius: radius.sm,
  },
  charCount: {
    fontFamily: fonts.pixel,
    fontSize: 6,
    color: colors.grey1,
    textAlign: 'right',
  },
  charCountWarning: {
    color: '#cc2200',
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: spacing.md,
    opacity: 0.6,
  },

  // Voice box — now clearly visible
  voiceBox: {
    alignItems: 'center',
    paddingVertical: spacing.md,
    marginBottom: spacing.xs,
    backgroundColor: 'rgba(13,10,30,0.95)',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.sm,
    padding: spacing.md,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  voiceBtn: {
    backgroundColor: 'rgba(255,107,0,0.15)',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.sm,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  voiceBtnStop: {
    backgroundColor: 'rgba(204,34,0,0.15)',
    borderWidth: 1,
    borderColor: '#cc2200',
    borderRadius: radius.sm,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  voiceBtnText: {
    fontFamily: fonts.pixel,
    fontSize: 9,
    color: colors.white,
    letterSpacing: 1,
  },
  recordingLabel: {
    fontFamily: fonts.pixel,
    fontSize: 7,
    color: '#cc2200',
    letterSpacing: 2,
  },
  audioReady: {
    alignItems: 'center',
    gap: 8,
  },
  audioReadyText: {
    fontFamily: fonts.pixel,
    fontSize: 8,
    color: colors.accent,
    textShadowColor: colors.accent,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  retakeText: {
    fontFamily: fonts.pixel,
    fontSize: 7,
    color: colors.grey1,
  },

  // Metadata
  metaBox: {
    backgroundColor: 'rgba(13,10,30,0.9)',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    padding: spacing.md,
    marginBottom: spacing.xs,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
  },
  metaDivider: {
    height: 1,
    backgroundColor: colors.border,
    opacity: 0.5,
  },
  metaKey: {
    fontFamily: fonts.pixel,
    fontSize: 6,
    color: colors.grey1,
    letterSpacing: 1,
  },
  metaVal: {
    fontFamily: fonts.mono,
    fontSize: 10,
    color: colors.accent,
    fontWeight: '900',
    maxWidth: '60%',
    textAlign: 'right',
  },

  // Success
  successBox: {
    backgroundColor: 'rgba(0,255,100,0.06)',
    borderWidth: 1,
    borderColor: '#00ff88',
    borderRadius: radius.sm,
    padding: spacing.md,
    gap: 6,
  },
  successTitle: {
    fontFamily: fonts.pixel,
    fontSize: 8,
    color: '#00ff88',
  },
  successUrl: {
    fontFamily: fonts.mono,
    fontSize: 10,
    color: '#00ff88',
    fontWeight: '900',
  },

  // Action button
  actionBtnWrapper: {
    width: '100%',
    borderRadius: radius.sm,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: colors.white,
    marginBottom: spacing.md,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 6,
  },
  actionBtnGradient: {
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBtnText: {
    fontFamily: fonts.pixel,
    fontSize: 10,
    color: colors.white,
    letterSpacing: 1,
  },
  actionBtnDisabled: {
    opacity: 0.5,
  },
  bottomLabel: {
    fontFamily: fonts.pixel,
    fontSize: 6,
    color: colors.grey2,
    textAlign: 'center',
    letterSpacing: 2,
  },
});